// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjJScfQXd0HMhY44NE6rHg0fBHsEolJiw',
    appId: '1:107902371501:web:b418cfcfdf4ed091b16824',
    messagingSenderId: '107902371501',
    projectId: 'transparencia-municipal-4e915',
    authDomain: 'transparencia-municipal-4e915.firebaseapp.com',
    storageBucket: 'transparencia-municipal-4e915.firebasestorage.app',
    measurementId: 'G-58HX112X2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqB9jxUQ_lIO4FcARxblQD2wHEg4QkP3A',
    appId: '1:107902371501:android:57b421697d51ce98b16824',
    messagingSenderId: '107902371501',
    projectId: 'transparencia-municipal-4e915',
    storageBucket: 'transparencia-municipal-4e915.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr0NYqSyG0dDar7iKWLVUkt9_5SU6PR44',
    appId: '1:107902371501:ios:54ea3e1f258844bfb16824',
    messagingSenderId: '107902371501',
    projectId: 'transparencia-municipal-4e915',
    storageBucket: 'transparencia-municipal-4e915.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr0NYqSyG0dDar7iKWLVUkt9_5SU6PR44',
    appId: '1:107902371501:ios:54ea3e1f258844bfb16824',
    messagingSenderId: '107902371501',
    projectId: 'transparencia-municipal-4e915',
    storageBucket: 'transparencia-municipal-4e915.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjJScfQXd0HMhY44NE6rHg0fBHsEolJiw',
    appId: '1:107902371501:web:f03c718d014a9928b16824',
    messagingSenderId: '107902371501',
    projectId: 'transparencia-municipal-4e915',
    authDomain: 'transparencia-municipal-4e915.firebaseapp.com',
    storageBucket: 'transparencia-municipal-4e915.firebasestorage.app',
    measurementId: 'G-B5Q9W95NZR',
  );
}
